### PR TITLE
Redis Actor Count 1:1:1:1

### PR DESCRIPTION
**Pull request by thesammiller**
Here is a basic implementation of the first experiment from the Actor Count. I'm also including some preliminary results, run manually on three m1.xlarge instances (8 CPUs, 16GB RAM) for the 1 producer VM - 1 producer process - 1 consumer VM - 1 consumer process (with 1 Redis VM and 1 Redis process). 

I added some columns to the pub/sub output for my own readability, but I don't think that should be an issue. The merge conflicts are with the README and I'm not sure how to fix that. This version should be the latest.

There are also some utility files here for processing, including `latency.py` and `throughput.py` to process pub/sub output and `metrics.py` in the Results folder for calculating min/max/average/standard deviation. 

Please let me know if you have any feedback. There are some Ansible tasks recording the installation process for Redis and Python dependencies.

### CODE REVIEW

**Review by TheENGR — APPROVED** [review]

**Review by TheENGR — DISMISSED** [review]

**Review by TheENGR — COMMENTED** [review]
Can you remove the __pycache__ folders?

**Comment by thesammiller** [comment]
__pycache__ should be removed now. Will also update this based on the new test standards.

**Comment by TheENGR** [comment]
> **pycache** should be removed now. Will also update this based on the new test standards.

I still see a few
image

**Comment by thesammiller** [comment]
And that's why you don't multitask.

**Review by gentryae — APPROVED** [review]

**Pull request merged**
